Build Error:
ERROR in src/app/pathId/pathId.page.ts:289:10 - error TS2551: Property 'togglePo
isNearToMe' does not exist on type 'PathIdPage'. Did you mean 'toggleShopsNearTo
Me'?
289 this.togglePoisNearToMe = !this.togglePoisNearToMe